# Generated by Django 6.0.3 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=600)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, related_name='projects', to='projects.projectfile')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
                'ordering': ['-name'],
                'unique_together': {('name', 'created_at')},
            },
        ),
    ]
